SAVEERROR_PATH = 'data/errors/errors.txt'
HISTORY_PATH = 'data/history/history.json'
USERS_HISTORY_PATH = 'data/history/user_history.json'
LEARNING_DATA_PATH = 'data/learning/learning_data.json'
MODELS_DATA_PATH = 'data/models/learning_data.json'
AI_API_KEY = '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'
QWEN_API_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMwYjhmMzMwLTczMGQtNDRlNi1hNjZlLTNiZmU4ODI4MWQ1NyIsImV4cCI6MTc0NTQwNDIyOX0.nFQ78sY2vkQPstUl79dhpYiBh71dr53mq0yzk7-9qlI'